Ditto SDK 4.2.2
getditto/demoapp-chat pull request #74
Opened 2023-07-05 15:17 UTC by kndoshn

2023-07-10 14:05 UTC, abunur commented
I've tested Android on 4.2.3 and it works great. I would recommend bumping the version to the latest SDK.

2023-07-10 15:37 UTC, abunur requested changes
I've tested Android on 4.2.3 and it works great. I would recommend bumping the version to the latest SDK. 4.2.2 is problematic on iOS which is why the new version came out so quickly.

2023-07-24 17:48 UTC, okdistribute approved these changes

2023-07-27 17:02 UTC, abunur commented
@kndoshn you can close this PR without merging, main is already on a later version of Ditto Android SDK

2023-07-27 20:15 UTC, closed without merging